name: edconnect
description: "A platform for teachers and students to interact"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  dropdown_textfield: ^1.2.0
  firebase_auth: ^5.1.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.2

  firebase_core: ^3.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  android: false
  ios: true
  web: false

  color: "#D8F3DC"
  image: "assets/images/logo.png"
  branding: "assets/images/branding.png"

  color_dark: "#081C15"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/branding.png
  fullscreen: true

  android_12:
    color: "#D8F3DC"
    image: "assets/images/logo.png"
    branding: "assets/images/branding.png"
    fullscreen: true

    color_dark: "#081C15"
    image_dark: assets/images/logo.png
    branding_dark: assets/images/branding.png

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
